# Generated by Django 4.1.5 on 2023-01-21 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Categoria',
            new_name='Genero',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='idCategoria',
            new_name='idGenero',
        ),
        migrations.RenameField(
            model_name='genero',
            old_name='nombreCategoria',
            new_name='nombreGenero',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='categoria',
            new_name='genero',
        ),
    ]
