# Generated by Django 4.1.5 on 2023-01-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_categoria_genero_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagenes', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='idGenero',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Genero Id'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rut',
            field=models.CharField(max_length=15, primary_key=True, serialize=False, verbose_name='Rut'),
        ),
    ]
